
#version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile_local_machine
    container_name: virtual_workspace_app_prod
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - .env
    network_mode: "host"  # allows dockcontainer to use your local machine network
    volumes:
      - .:/app
