
#version: "3.9"

services:
  app:
    build: .
    container_name: virtual_workspace_room_booking_app
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - .env
    network_mode: "host"  # allows dockcontainer to use your local machine network
    volumes:
      - .:/app
