
#version: "3.9"

services:

  db:
    image: mysql:8.0
    container_name: virtual_workspace_mysql_prod
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DB_NAME}
      MYSQL_USER: ${MYSQL_DB_USER}
      MYSQL_PASSWORD: ${MYSQL_DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db/dump_data.sql:/docker-entrypoint-initdb.d/dump_data.sql
    networks:
      - workspace_network

  app:
    build: .
    container_name: virtual_workspace_app_prod
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - .:/app
    command: >
      sh -c "uvicorn main:app --host 0.0.0.0 --port 8000"
    networks:
      - workspace_network

volumes:
  mysql_data:

networks:
  workspace_network:
    driver: bridge
